<?php
    session_start();
    
    if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    if (isset($_GET['choice'])) {
        $choice = $_GET['choice'];
        switch ($choice) {
            case 'choice-1':
                header('Location: page2.phtml');
                exit;
            case 'choice-2':
                header('Location: page3.phtml');
                exit;
            case 'choice-3':
                header('Location: page4.phtml');
                exit;
            default:
        }
    }
}
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice">
<main>
    <section>
        <h2>Description du choix à faire</h2>
        <div>
            <form method="get" action="">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="page2.phtml">Choix 1</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="page3.phtml">Choix 2</label>
                </div>
                <div>
                    <input type="radio" id="choice-3" name="choice" value="choice-3">
                    <label for="page4.phtml">Choix 3</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/door.png" />
            <h1>PAGE 4 BLABLA <?php echo $_SESSION['heroName']; ?> vous attrapez le scorbut</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>