<?php
    session_start();
    
    if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    if (isset($_GET['choice'])) {
        $choice = $_GET['choice'];
        switch ($choice) {
            case 'choice-1':
                header('Location: page3.phtml');
                exit;
            case 'choice-2':
                header('Location: page4.phtml');
                exit;
            default:
        }
    }
}
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice">
<main>
    <section>
        <h2>Prochaine direction ?</h2>
        <div>
            <form method="get" action="">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">le Nouveau Monde !</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="choice-2">Grand Line !</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="https://media.giphy.com/media/iNiHLhB3jAcaJKzWPk/giphy.gif" />
            <h1>Alors que vous explorez le bateau-restaurant Baratie, Sanji, chef cuisinier et combattant talentueux, attire votre attention. Lorsque le bateau est attaqué par des pirates, vous intervenez pour le défendre. Impressionné par votre courage, Sanji accepte de rejoindre votre équipage. "C'est un honneur, camarade," déclare-t-il, "je me joindrai à votre quête du All Blue à bord de votre bateau !" Votre équipage gagne un nouvel membre précieux.</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>